gogo/gogo/gogo/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

gogo/gogo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('gogoapp/', include('gogoapp.urls')),
    path('gogoapp/', include('django.contrib.auth.urls')),
]

gogo/gogoapp/urls.py
from django.urls import path
from .views import SignUpView
from . import views

#app_name = 'gogoapp'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('signup/validate_username', views.validate_username, name='validate_username'),
    path('signup/validate_email', views.validate_email, name='validate_email'),
    path('welcome',views.welcome, name='welcome'),
    path('welcome/get_statistics',views.get_statistics, name='get_statistics'),
    path('welcome/create_game',views.create_game, name='create_game'),
    path('welcome/accept_game',views.accept_game, name='accept_game'),
    path('welcome/refuse_game',views.refuse_game, name='refuse_game'),
    path('game/<int:number>', views.game, name='game'),
    path('game/<int:number>/get_params', views.get_params, name='get_params'),

    path('signup_mobile',views.signup_mobile, name='signup_mobile'),
    path('login_mobile',views.login_mobile, name='login_mobile'),
]

gogo/gogoapp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django_mysql.models import ListTextField

class CustomUser(AbstractUser):
    nationality = models.CharField(max_length=50,default='',blank=False)
    elo = models.IntegerField(default=500)
    win = models.IntegerField(default=0)
    lose = models.IntegerField(default=0)
    winrate = models.FloatField(default=0)
    loserate = models.FloatField(default=0)
    best_elo = models.IntegerField(default=500)
    channel_name = models.CharField(max_length=100,default='')
    def __str__(self):
        return self.username

class QueueGame(models.Model):
   username = models.CharField(max_length=50)
   elo = models.IntegerField()
   time = models.CharField(max_length=50)
   dim = models.CharField(max_length=50)
   playerName = models.CharField(max_length=50,default='')
   random = models.CharField(max_length=50,default='')
   refuse = models.CharField(max_length=50,default='')

class Gaming(models.Model):
   username1 = models.CharField(max_length=50)
   username2 = models.CharField(max_length=50)
   elo1 = models.IntegerField()
   elo2 = models.IntegerField()
   time1 = models.IntegerField(default=0)
   time2 = models.IntegerField(default=0)
   timer1 = models.IntegerField(default=0)
   timer2 = models.IntegerField(default=0)
   eat_ball = models.IntegerField(default=-1)
   dim = models.IntegerField(default=9)
   id_move = models.IntegerField(default=0)
   moves = ListTextField(base_field=models.IntegerField(default=0),size=500, default=0)
   hash_code = models.IntegerField(default=0)
   score1 = models.IntegerField(default=0)
   score2 = models.FloatField(default=5.5)
   pedine1 = models.IntegerField(default=0)
   pedine2 = models.IntegerField(default=0)
   pass_flag = models.IntegerField(default=0)
   last_move = models.IntegerField(default=0)

class History(models.Model):
  winner = models.CharField(max_length=50)
  loser = models.CharField(max_length=50)
  hash_code = models.IntegerField(default=0)
  victory = models.IntegerField(default=0)

gogo/gogoapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser, QueueGame

class CustomUserCreationForm(UserCreationForm):
    nationality = forms.CharField(help_text="nationality")
    class Meta:
        model = CustomUser
        fields = ('username', 'email','nationality')

class CustomUserChangeForm(UserChangeForm):
    nationality = forms.CharField(help_text="nationality")
    class Meta:
        model = CustomUser
        fields = ('username', 'email','nationality')

class QueueGameForm(forms.Form):
   dim = forms.CharField(required=True,help_text="dim")
   time = forms.CharField(required=True,help_text="time")
   playerName = forms.CharField(required=False,help_text="playerName")
   random = forms.CharField(required=False,help_text="random")
   class Meta:
        model = QueueGame
        fields = ('dim','time','playerName','random')

gogo/gogoapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic.edit import CreateView
from django.contrib.auth.hashers import make_password, check_password
from django.http import JsonResponse, HttpResponse,HttpResponseRedirect
from django.template import loader
from django.db.models import Q
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required

import re
import json

from .forms import CustomUserCreationForm, QueueGameForm
from .models import CustomUser, QueueGame, Gaming, History
from .methods import update_pass, update_surrender, statistics, create_a_game, accept_a_game, get_current_game

#Signup/Login handler for web app (CSRF protection)
class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

#Signup handler for mobile app (no CSRF protection needed)
@csrf_exempt
def signup_mobile(request):
   registered = False
   if request.method == 'POST':
       bytes = request.body
       user = json.loads(bytes)
       username = user["username"]
       email = user["email"]
       nationality = user["nationality"]
       password = user["password"]
       password = make_password(password)
       u = CustomUser(username = username, email = email, nationality = nationality, password = password)
       u.save()
       registered = True
   data = {'registered' : registered}
   return JsonResponse(data)

#Login handler for mobile app (no CRSF protection needed)
@csrf_exempt
def login_mobile(request):
   authenticated = False
   if request.method == 'POST':
       bytes = request.body
       user = json.loads(bytes)
       username = user["username"]
       password = user["password"]
       user =  CustomUser.objects.filter(Q(username__iexact=username))
       if user:
         user = user[0]
         if user.username == username and check_password(password,user.password):
           authenticated = True
   data = {'authenticated' : authenticated}
   return JsonResponse(data)

#Called each time welcome is rendered
def get_statistics(request):
    username = request.GET.get('username', None)
    data = statistics(username)
    return JsonResponse(data)

#Check if username already exists or is in invalid format
def validate_username(request):
        username = request.GET.get('username', None)
        match = re.search(r'^[a-zA-Z0-9]+([a-zA-Z0-9](_|-| )[a-zA-Z0-9])*[a-zA-Z0-9]+$', username, re.I)
        if match:
          is_valid = True
        else:
          is_valid = False
        data = { 'is_taken' : CustomUser.objects.filter(username__iexact=username).exists(), 'is_valid' : is_valid }
        return JsonResponse(data)


#Check if email already exists or is in invalid format
def validate_email(request):
        email = request.GET.get('email', None)
        is_valid = True
        is_taken = False
        if email != '':
            match = re.search(r'^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$', email, re.I)
            if not match:
                is_valid = False
            else:
                is_taken = CustomUser.objects.filter(email__iexact=email).exists()
        data = { 'is_taken' : is_taken , 'is_valid' : is_valid }
        return JsonResponse(data)


#Render welcome template for web app
#@login_required
def welcome(request):
        username = request.user.username
        current_game = Gaming.objects.filter(Q(username1__iexact=username) | Q(username2__iexact=username))
        if current_game:
            hash_code = current_game[0].hash_code
            return HttpResponseRedirect(reverse('game', args=(hash_code,)))
        context = {'username':username}
        template = loader.get_template('welcome.html')
        return HttpResponse(template.render(context,request))


@csrf_exempt
def create_game(request):
        print("create game")
        data = {}
        if request.method == 'POST':
            data = create_a_game(request)
        return JsonResponse(data)

@csrf_exempt
def accept_game(request):
        data = {}
        if request.method == 'POST':
            data = accept_a_game(request)
        return JsonResponse(data)

@csrf_exempt
def refuse_game(request):
        data = {}
        if request.method == 'POST':
           bytes = request.body
           params = json.loads(bytes)
           username = params["username"]
           playername = params["playername"]
           QueueGame.objects.filter(Q(username__iexact=playername) & Q(random__iexact='0')).update(refuse='2')
        return JsonResponse(data)


#Render game template if game is found for user, or render welcome page
def game(request,number):
       current_game = Gaming.objects.filter(hash_code__iexact=number)
       if current_game:
           context = {'username': request.user.username,'hash_code' : number}
           template = loader.get_template('game.html')
           return HttpResponse(template.render(context,request))
       else:
           return redirect("welcome")

#Called each time game template is rendered to get game status
def get_params(request,number):
       data = {}
       userRequest = request.GET.get('username',None)
       current_game = Gaming.objects.filter(hash_code__iexact=number)
       if current_game:
           data = get_current_game(current_game, userRequest,number)
       return JsonResponse(data)

gogo/gogoapp/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}GoGoApp{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
    {% load static %}
    <!--script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>

    <script src="https://unpkg.com/react@16/umd/react.production.min.js"></script>
    <script src="https://unpkg.com/react-dom@16/umd/react-dom.production.min.js"></script>
    <script src="https://unpkg.com/babel-standalone@6.15.0/babel.min.js"></script>
    <script src="https://unpkg.com/@material-ui/core@latest/umd/material-ui.development.js"></script>
    <script src="https://unpkg.com/@material-ui/core@latest/umd/material-ui.production.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react-chartjs-2/2.1.0/react-chartjs-2.min.js"></script-->


    <script type="text/javascript" src="{% static 'js/dependencies/jquery_3.1.1.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/dependencies/react_16.13.1.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/dependencies/react_dom_16.13.1.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/dependencies/babel_6.15.0.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/dependencies/material_ui_4.9.8.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/dependencies/material_ui_production_4.9.8.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/dependencies/chart_js_2.8.0.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/dependencies/react_chartjs_2.1.0.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/dependencies/react_websocket_2.1.0.js' %}"></script>

    {%block javascript %}
    {% endblock %}
  </main>
</body>
</html>

gogo/gogoapp/templates/game.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
  <div id="game"></div>
  <script type="text/javascript">
    var data = {
      username: '{{username}}',
      hash_code: '{{hash_code}}'
    };
  </script>
  {% load static %}
    <script type="text/babel" src="{% static 'js/game.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/game.css' %}">
{% endblock %}

gogo/gogoapp/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
 {% if user.is_authenticated %}
  <meta http-equiv="Refresh" content="0; {% url 'welcome' %}" />
 {% else %}
    <div id="root">    
      <div id="image">
       <div id="title"> GoGoApp </div> 
       <button id="login" onClick="window.location.href = '{% url 'login' %}'">Login</button> 
       <button id="signup" onClick="window.location.href = '{% url 'signup' %}'">Signup</button>
      </div>
    </div>
 {% endif %}
{% endblock %}

gogo/gogoapp/templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block javascript %}
  <script type="text/javascript">
    $("#id_username").change(function () {
    var username = $(this).val();
    var txt = "";
      $.ajax({
        url: 'validate_username',
        data: {
          'username': username
        },
        dataType: 'json',
        success: function (data) {
          if (data.is_taken) {
            txt = "Username already exists";
            $("#error-user").text(txt);
          }
          else {
            $("#error-user").empty();
          }
        }
      });

    });
  </script>
  <script type="text/javascript">
    $("#id_email").change(function () {
    var email = $(this).val();
    var txt = "";
      $.ajax({
        url: 'validate_email',
        data: {
          'email': email
        },
        dataType: 'json',
        success: function (data) {
          if (data.is_taken) {
            txt = "Email already exists";
            $("#error-email").text(txt); 
          }
          else{
            $("#error-email").empty();
          }
        }
      });

    });
  </script>
{% endblock %}

{% block content %}
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/signup.css' %}">
  <div id="body">
    <div id="root"> 
     <form method="post">
      {% csrf_token %}
      <div id="title">Sign Up</div>
      <div id="label-user">
        <label for="id_username">Username:</label>
      </div>
      <div id="input-user">
        <input type="text" name="username" placeholder="Username" maxlength="20" autofocus required id="id_username">
      </div>
      <div id="span-user">
        <span  id="error-user"> </span>
      </div>
      {% if form.errors.username %}
        <div id="span-user2">
          <span id="e-user"> {{form.errors.username}}</span>
        </div>
      {% endif %}
      <div id="label-email">
        <label for="id_email">Email address (optional):</label>
      </div>
      <div id="input-email">
        <input type="email" name="email" placeholder="Email" maxlength="30" id="id_email">
      </div>
      <div id="span-email2">
        <span  id="error-email"> </span>
      </div>
      {% if form.errors.email %}
        <div id="span-email">
          <span id="e-email"> {{form.errors.email}}</span>
        </div>
      {% endif %}
      <div id="label-nation">
        <label for="id_nationality">Nationality:</label>
      </div>
      <div id="input-nation">
        <select required name="nationality">
  <option value="">-- select one --</option>
  <option value="afghan">Afghan</option>
  <option value="albanian">Albanian</option>
  <option value="algerian">Algerian</option>
  <option value="american">American</option>
  <option value="andorran">Andorran</option>
  <option value="angolan">Angolan</option>
  <option value="antiguans">Antiguans</option>
  <option value="argentinean">Argentinean</option>
  <option value="armenian">Armenian</option>
  <option value="australian">Australian</option>
  <option value="austrian">Austrian</option>
  <option value="azerbaijani">Azerbaijani</option>
  <option value="bahamian">Bahamian</option>
  <option value="bahraini">Bahraini</option>
  <option value="bangladeshi">Bangladeshi</option>
  <option value="barbadian">Barbadian</option>
  <option value="barbudans">Barbudans</option>
  <option value="batswana">Batswana</option>
  <option value="belarusian">Belarusian</option>
  <option value="belgian">Belgian</option>
  <option value="belizean">Belizean</option>
  <option value="beninese">Beninese</option>
  <option value="bhutanese">Bhutanese</option>
  <option value="bolivian">Bolivian</option>
  <option value="bosnian">Bosnian</option>
  <option value="brazilian">Brazilian</option>
  <option value="british">British</option>
  <option value="bruneian">Bruneian</option>
  <option value="bulgarian">Bulgarian</option>
  <option value="burkinabe">Burkinabe</option>
  <option value="burmese">Burmese</option>
  <option value="burundian">Burundian</option>
  <option value="cambodian">Cambodian</option>
  <option value="cameroonian">Cameroonian</option>
  <option value="canadian">Canadian</option>
  <option value="cape verdean">Cape Verdean</option>
  <option value="central african">Central African</option>
  <option value="chadian">Chadian</option>
  <option value="chilean">Chilean</option>
  <option value="chinese">Chinese</option>
  <option value="colombian">Colombian</option>
  <option value="comoran">Comoran</option>
  <option value="congolese">Congolese</option>
  <option value="costa rican">Costa Rican</option>
  <option value="croatian">Croatian</option>
  <option value="cuban">Cuban</option>
  <option value="cypriot">Cypriot</option>
  <option value="czech">Czech</option>
  <option value="danish">Danish</option>
  <option value="djibouti">Djibouti</option>
  <option value="dominican">Dominican</option>
  <option value="dutch">Dutch</option>
  <option value="east timorese">East Timorese</option>
  <option value="ecuadorean">Ecuadorean</option>
  <option value="egyptian">Egyptian</option>
  <option value="emirian">Emirian</option>
  <option value="equatorial guinean">Equatorial Guinean</option>
  <option value="eritrean">Eritrean</option>
  <option value="estonian">Estonian</option>
  <option value="ethiopian">Ethiopian</option>
  <option value="fijian">Fijian</option>
  <option value="filipino">Filipino</option>
  <option value="finnish">Finnish</option>
  <option value="french">French</option>
  <option value="gabonese">Gabonese</option>
  <option value="gambian">Gambian</option>
  <option value="georgian">Georgian</option>
  <option value="german">German</option>
  <option value="ghanaian">Ghanaian</option>
  <option value="greek">Greek</option>
  <option value="grenadian">Grenadian</option>
  <option value="guatemalan">Guatemalan</option>
  <option value="guinea-bissauan">Guinea-Bissauan</option>
  <option value="guinean">Guinean</option>
  <option value="guyanese">Guyanese</option>
  <option value="haitian">Haitian</option>
  <option value="herzegovinian">Herzegovinian</option>
  <option value="honduran">Honduran</option>
  <option value="hungarian">Hungarian</option>
  <option value="icelander">Icelander</option>
  <option value="indian">Indian</option>
  <option value="indonesian">Indonesian</option>
  <option value="iranian">Iranian</option>
  <option value="iraqi">Iraqi</option>
  <option value="irish">Irish</option>
  <option value="israeli">Israeli</option>
  <option value="italian">Italian</option>
  <option value="ivorian">Ivorian</option>
  <option value="jamaican">Jamaican</option>
  <option value="japanese">Japanese</option>
  <option value="jordanian">Jordanian</option>
  <option value="kazakhstani">Kazakhstani</option>
  <option value="kenyan">Kenyan</option>
  <option value="kittian and nevisian">Kittian and Nevisian</option>
  <option value="kuwaiti">Kuwaiti</option>
  <option value="kyrgyz">Kyrgyz</option>
  <option value="laotian">Laotian</option>
  <option value="latvian">Latvian</option>
  <option value="lebanese">Lebanese</option>
  <option value="liberian">Liberian</option>
  <option value="libyan">Libyan</option>
  <option value="liechtensteiner">Liechtensteiner</option>
  <option value="lithuanian">Lithuanian</option>
  <option value="luxembourger">Luxembourger</option>
  <option value="macedonian">Macedonian</option>
  <option value="malagasy">Malagasy</option>
  <option value="malawian">Malawian</option>
  <option value="malaysian">Malaysian</option>
  <option value="maldivan">Maldivan</option>
  <option value="malian">Malian</option>
  <option value="maltese">Maltese</option>
  <option value="marshallese">Marshallese</option>
  <option value="mauritanian">Mauritanian</option>
  <option value="mauritian">Mauritian</option>
  <option value="mexican">Mexican</option>
  <option value="micronesian">Micronesian</option>
  <option value="moldovan">Moldovan</option>
  <option value="monacan">Monacan</option>
  <option value="mongolian">Mongolian</option>
  <option value="moroccan">Moroccan</option>
  <option value="mosotho">Mosotho</option>
  <option value="motswana">Motswana</option>
  <option value="mozambican">Mozambican</option>
  <option value="namibian">Namibian</option>
  <option value="nauruan">Nauruan</option>
  <option value="nepalese">Nepalese</option>
  <option value="new zealander">New Zealander</option>
  <option value="ni-vanuatu">Ni-Vanuatu</option>
  <option value="nicaraguan">Nicaraguan</option>
  <option value="nigerien">Nigerien</option>
  <option value="north korean">North Korean</option>
  <option value="northern irish">Northern Irish</option>
  <option value="norwegian">Norwegian</option>
  <option value="omani">Omani</option>
  <option value="pakistani">Pakistani</option>
  <option value="palauan">Palauan</option>
  <option value="panamanian">Panamanian</option>
  <option value="papua new guinean">Papua New Guinean</option>
  <option value="paraguayan">Paraguayan</option>
  <option value="peruvian">Peruvian</option>
  <option value="polish">Polish</option>
  <option value="portuguese">Portuguese</option>
  <option value="qatari">Qatari</option>
  <option value="romanian">Romanian</option>
  <option value="russian">Russian</option>
  <option value="rwandan">Rwandan</option>
  <option value="saint lucian">Saint Lucian</option>
  <option value="salvadoran">Salvadoran</option>
  <option value="samoan">Samoan</option>
  <option value="san marinese">San Marinese</option>
  <option value="sao tomean">Sao Tomean</option>
  <option value="saudi">Saudi</option>
  <option value="scottish">Scottish</option>
  <option value="senegalese">Senegalese</option>
  <option value="serbian">Serbian</option>
  <option value="seychellois">Seychellois</option>
  <option value="sierra leonean">Sierra Leonean</option>
  <option value="singaporean">Singaporean</option>
  <option value="slovakian">Slovakian</option>
  <option value="slovenian">Slovenian</option>
  <option value="solomon islander">Solomon Islander</option>
  <option value="somali">Somali</option>
  <option value="south african">South African</option>
  <option value="south korean">South Korean</option>
  <option value="spanish">Spanish</option>
  <option value="sri lankan">Sri Lankan</option>
  <option value="sudanese">Sudanese</option>
  <option value="surinamer">Surinamer</option>
  <option value="swazi">Swazi</option>
  <option value="swedish">Swedish</option>
  <option value="swiss">Swiss</option>
  <option value="syrian">Syrian</option>
  <option value="taiwanese">Taiwanese</option>
  <option value="tajik">Tajik</option>
  <option value="tanzanian">Tanzanian</option>
  <option value="thai">Thai</option>
  <option value="togolese">Togolese</option>
  <option value="tongan">Tongan</option>
  <option value="trinidadian or tobagonian">Trinidadian or Tobagonian</option>
  <option value="tunisian">Tunisian</option>
  <option value="turkish">Turkish</option>
  <option value="tuvaluan">Tuvaluan</option>
  <option value="ugandan">Ugandan</option>
  <option value="ukrainian">Ukrainian</option>
  <option value="uruguayan">Uruguayan</option>
  <option value="uzbekistani">Uzbekistani</option>
  <option value="venezuelan">Venezuelan</option>
  <option value="vietnamese">Vietnamese</option>
  <option value="welsh">Welsh</option>
  <option value="yemenite">Yemenite</option>
  <option value="zambian">Zambian</option>
  <option value="zimbabwean">Zimbabwean</option></select>
      </div>
      <div id="label-pass1">
        <label for="id_password1">Password:</label>
      </div>
      <div id="input-pass1">
        <input type="password" name="password1" placeholder="Password" maxlength=32 autocomplete="new-password" required id="id_password1">
      </div>
      {% if form.errors.password2 %}
        <div id="span-password1">
          <span id="e-pass1"> <ul><li>Your password can’t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can’t be a commonly used password.</li><li>Your password can’t be entirely numeric.</li></ul></span>
        </div>
      {% endif %}
      <div id="label-pass2">
        <label for="id_password2">Password confirmation:</label>
      </div>
      <div id="input-pass2">
        <input type="password" name="password2" placeholder="Confirm Password" maxlength=32 autocomplete="new-password" required id="id_password2">
      </div>
      {% if form.errors.password2 %}
        <div id="span-password2">
          <span id="e-pass2"> Enter the same password as before, for verification. </span>
        </div>
      {% endif %}
      <button id="submit" type="submit">Sign up</button> 
     </form>
    </div>
  </div>
{% endblock %}

gogo/gogoapp/templates/welcome.html
{% extends 'base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
  {% if not user.is_authenticated %}
    <meta http-equiv="Refresh" content="0; {% url 'home' %}" />
  {% else %}
    <div id="welcome"></div>
      <script type="text/javascript">
        var data = {
          username: '{{username}}',
        };
      </script>
  {% load static %}
    <script type="text/babel" src="{% static 'js/welcome.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/welcome.css' %}">
  {% endif %}
{% endblock %}